language: general

services:
  - docker

branches:
  only:
    - master

before_script:
  - chmod +x *.sh
    # Avoid BiocCheck > checkCodingPractice > checkLogicalUseFiles error.
  - touch inst/rmarkdown/templates/differential-expression/skeleton/_{footer,header,links}.Rmd

jobs:
  include:
    - stage: test
      name: "bioc-3.9"
      script: image="rnaseq" tag="bioc-3.9" ./docker.sh
    - stage: test
      name: "bioc-devel"
      script: image="rnaseq" tag="bioc-devel" ./docker.sh

matrix:
  allow_failures:
    - name: "bioc-devel"
  fast_finish: true

after_failure:
  - ./docker-failure.sh

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
